services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./app:/app"
    command: "make dev"
  db:
    volumes:
      - "./app/data:/var/lib/postgresql/data"
  caddy:
    image: caddy
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app