services:
  app:
    image: xfuuserx1/devops-for-programmers-project-74
    build:
      context: ./
      dockerfile: Dockerfile.production
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - "./data:/var/lib/postgresql/data"
    env_file:
      - "./app/.env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5