version: '3'
services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    build: Dockerfile
    volumes:
      - "./app:/app"
  db:
    extends:
      file: docker-compose.yml
      service: db
    volumes:
      - "./app/data:/var/lib/postgresql/data"